openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts APP
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Contact App
tags:
  - name: Contacts
    description: Contacts operations.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://nodejs-hw-mongodb-7xq4.onrender.com
    description: Production server
  - url: http://localhost:3000
    description: Local server
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refreshUserSession.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/sendResetEmail.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/resetPwd.yaml
  /auth/get-oauth-url:
    get:
      $ref: ../swagger/paths/auth/get-oauth-url.yaml
  /auth/confirm-oauth:
    post:
      $ref: ../swagger/paths/auth/confirm-oauth.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer